---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: clusterproviderdescs.logicalcluster.kubestellar.io
spec:
  group: logicalcluster.kubestellar.io
  names:
    kind: ClusterProviderDesc
    listKind: ClusterProviderDescList
    plural: clusterproviderdescs
    shortNames:
    - cpc
    singular: clusterproviderdesc
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterProviderDesc represents a provider.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: '`spec` describes a provider.'
            properties:
              ClusterPrefixForDiscovery:
                description: ClusterPrefixForDiscovery contains the prefix used during
                  cluster discovery.
                type: string
              Config:
                description: 'TODO: this should be stored as a secret! Config is the
                  provider config'
                type: string
              ProviderType:
                description: ProviderType is the type of the provider of the cluster.
                type: string
                x-kubernetes-validations:
                - message: cluster is immutable
                  rule: self == oldSelf
            required:
            - ProviderType
            type: object
          status:
            description: '`status` describes the status of the provider object.'
            properties:
              Phase:
                default: Initializing
                description: Phase of the provider (Initializing,Ready).
                enum:
                - Initializing
                - Ready
                type: string
            required:
            - Phase
            type: object
        type: object
    served: true
    storage: true
