---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: spaces.space.kubestellar.io
spec:
  group: space.kubestellar.io
  names:
    kind: Space
    listKind: SpaceList
    plural: spaces
    shortNames:
    - spa
    singular: space
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Space represents a cluster.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: '`spec` describes a cluster.'
            properties:
              Managed:
                default: true
                description: Managed identifies whether a cluster is managed (true)
                  or unmanaged (false). Currently this is immutable. A space can be
                  created through the ClusterManager (managed) or discovered/imported
                  (unmanaged).
                type: boolean
                x-kubernetes-validations:
                - message: Managed is immutable
                  rule: self == oldSelf
              SpaceProviderDescName:
                description: SpaceProviderDescName is a reference to a SpaceProviderDesc
                  resource
                type: string
                x-kubernetes-validations:
                - message: SpaceProviderDescName is immutable
                  rule: self == oldSelf
            required:
            - Managed
            - SpaceProviderDescName
            type: object
          status:
            description: '`status` describes the status of the cluster object.'
            properties:
              ClusterConfig:
                description: Cluster config from the kube config file in string format.
                type: string
              Phase:
                description: Phase of the space (Initializing,NotReady,Ready,Incompatible).
                enum:
                - Initializing
                - NotReady
                - Ready
                - Incompatible
                type: string
            type: object
        type: object
    served: true
    storage: true
