apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: edge.kcp.io
spec:
  latestResourceSchemas:
  - v230618-23cd8129.customizers.edge.kcp.io
  - v230618-23cd8129.edgeplacements.edge.kcp.io
  - v230618-23cd8129.edgesyncconfigs.edge.kcp.io
  - v230618-23cd8129.singleplacementslices.edge.kcp.io
  - v230618-23cd8129.syncerconfigs.edge.kcp.io
  - v230701-83e8956c.synctargets.edge.kcp.io
  - v230704-a60bb94c.locations.edge.kcp.io
status: {}
