apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: edge.kcp.io
spec:
  latestResourceSchemas:
  - v230227-655d6c9.customizers.edge.kcp.io
  - v230303-6f7f2fe.singleplacementslices.edge.kcp.io
  - v230317-d43d2d5.edgeplacements.edge.kcp.io
  - v230407-c87b2365.syncerconfigs.edge.kcp.io
  - v230413-5a4d4ba.edgesyncconfigs.edge.kcp.io
  - v230612-02e13145.clusterproviderdescs.edge.kcp.io
  - v230612-920e753e.logicalclusters.edge.kcp.io
status: {}
