apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: edge.kcp.io
spec:
  latestResourceSchemas:
  - v230618-23cd8129.customizers.edge.kcp.io
  - v230618-23cd8129.edgeplacements.edge.kcp.io
  - v230618-23cd8129.edgesyncconfigs.edge.kcp.io
  - v230618-23cd8129.syncerconfigs.edge.kcp.io
  - v230630-f011ab29.singleplacementslices.edge.kcp.io
status: {}
