apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: edge.kubestellar.io
spec:
  latestResourceSchemas:
  - v231005-c6f7728ef.customizers.edge.kubestellar.io
  - v231005-c6f7728ef.edgeplacements.edge.kubestellar.io
  - v231005-c6f7728ef.edgesyncconfigs.edge.kubestellar.io
  - v231005-c6f7728ef.locations.edge.kubestellar.io
  - v231005-c6f7728ef.singleplacementslices.edge.kubestellar.io
  - v231005-c6f7728ef.syncerconfigs.edge.kubestellar.io
  - v231005-c6f7728ef.synctargets.edge.kubestellar.io
status: {}
