apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: edge.kcp.io
spec:
  latestResourceSchemas:
  - v230227-655d6c9.customizers.edge.kcp.io
  - v230228-7fe2c02.edgeplacements.edge.kcp.io
  - v230303-6f7f2fe.singleplacementslices.edge.kcp.io
status: {}
