apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: v230625-4e520286a.logicalclusters.logicalcluster.kubestellar.io
spec:
  group: logicalcluster.kubestellar.io
  names:
    kind: LogicalCluster
    listKind: LogicalClusterList
    plural: logicalclusters
    shortNames:
    - ecl
    singular: logicalcluster
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      description: LogicalCluster represents a cluster.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: '`spec` describes a cluster.'
          properties:
            ClusterProviderDescName:
              description: ClusterProviderDescName is a reference to a ClusterProviderDesc
                resource
              type: string
              x-kubernetes-validations:
              - message: ClusterProviderDescName is immutable
                rule: self == oldSelf
            Managed:
              default: true
              description: Managed identifies whether a cluster is managed (true)
                or unmanaged (false). Currently this is immutable. A logical cluster
                can be created through the ClusterManager (managed) or discovered/imported
                (unmanaged).
              type: boolean
              x-kubernetes-validations:
              - message: Managed is immutable
                rule: self == oldSelf
          required:
          - ClusterProviderDescName
          - Managed
          type: object
        status:
          description: '`status` describes the status of the cluster object.'
          properties:
            ClusterConfig:
              description: Cluster config from the kube config file in string format.
              type: string
            Phase:
              default: Initializing
              description: Phase of the workspace (Initializing,NotReady,Ready).
              enum:
              - Initializing
              - NotReady
              - Ready
              type: string
          required:
          - Phase
          type: object
      type: object
    served: true
    storage: true
    subresources: {}
