apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.kubernetes.io: https://github.com/kcp-dev/kubernetes/pull/4
  creationTimestamp: null
  name: runtimeclasses.node.k8s.io
spec:
  conversion:
    strategy: None
  group: node.k8s.io
  names:
    kind: RuntimeClass
    listKind: RuntimeClassList
    plural: runtimeclasses
    singular: runtimeclass
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: RuntimeClass defines a class of container runtime supported in
          the cluster. The RuntimeClass is used to determine which container runtime
          is used to run all containers in a pod. RuntimeClasses are manually defined
          by a user or cluster provisioner, and referenced in the PodSpec. The Kubelet
          is responsible for resolving the RuntimeClassName reference before running
          the pod.  For more details, see https://kubernetes.io/docs/concepts/containers/runtime-class/
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          handler:
            description: Handler specifies the underlying runtime and configuration
              that the CRI implementation will use to handle pods of this class. The
              possible values are specific to the node & CRI configuration.  It is
              assumed that all handlers are available on every node, and handlers
              of the same name are equivalent on every node. For example, a handler
              called "runc" might specify that the runc OCI runtime (using native
              Linux containers) will be used to run the containers in a pod. The Handler
              must be lowercase, conform to the DNS Label (RFC 1123) requirements,
              and is immutable.
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          overhead:
            description: |-
              Overhead represents the resource overhead associated with running a pod for a given RuntimeClass. For more details, see
               https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/
            properties:
              podFixed:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                description: PodFixed represents the fixed resource overhead associated
                  with running a pod.
                type: object
            type: object
          scheduling:
            description: Scheduling holds the scheduling constraints to ensure that
              pods running with this RuntimeClass are scheduled to nodes that support
              it. If scheduling is nil, this RuntimeClass is assumed to be supported
              by all nodes.
            properties:
              nodeSelector:
                additionalProperties:
                  type: string
                description: nodeSelector lists labels that must be present on nodes
                  that support this RuntimeClass. Pods using this RuntimeClass can
                  only be scheduled to a node matched by this selector. The RuntimeClass
                  nodeSelector is merged with a pod's existing nodeSelector. Any conflicts
                  will cause the pod to be rejected in admission.
                type: object
              tolerations:
                description: tolerations are appended (excluding duplicates) to pods
                  running with this RuntimeClass during admission, effectively unioning
                  the set of nodes tolerated by the pod and the RuntimeClass.
                items:
                  description: The pod this Toleration is attached to tolerates any
                    taint that matches the triple <key,value,effect> using the matching
                    operator <operator>.
                  properties:
                    effect:
                      description: |-
                        Effect indicates the taint effect to match. Empty means match all taint effects. When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute.

                        Possible enum values:
                         - `"NoExecute"` Evict any already-running pods that do not tolerate the taint. Currently enforced by NodeController.
                         - `"NoSchedule"` Do not allow new pods to schedule onto the node unless they tolerate the taint, but allow all pods submitted to Kubelet without going through the scheduler to start, and allow all already-running pods to continue running. Enforced by the scheduler.
                         - `"PreferNoSchedule"` Like TaintEffectNoSchedule, but the scheduler tries not to schedule new pods onto the node, rather than prohibiting new pods from scheduling onto the node entirely. Enforced by the scheduler.
                      type: string
                    key:
                      description: Key is the taint key that the toleration applies
                        to. Empty means match all taint keys. If the key is empty,
                        operator must be Exists; this combination means to match all
                        values and all keys.
                      type: string
                    operator:
                      description: |-
                        Operator represents a key's relationship to the value. Valid operators are Exists and Equal. Defaults to Equal. Exists is equivalent to wildcard for value, so that a pod can tolerate all taints of a particular category.

                        Possible enum values:
                         - `"Equal"`
                         - `"Exists"`
                      type: string
                    tolerationSeconds:
                      description: TolerationSeconds represents the period of time
                        the toleration (which must be of effect NoExecute, otherwise
                        this field is ignored) tolerates the taint. By default, it
                        is not set, which means tolerate the taint forever (do not
                        evict). Zero and negative values will be treated as 0 (evict
                        immediately) by the system.
                      format: int64
                      type: integer
                    value:
                      description: Value is the taint value the toleration matches
                        to. If the operator is Exists, the value should be empty,
                        otherwise just a regular string.
                      type: string
                  type: object
                type: array
                x-kubernetes-list-type: atomic
            type: object
        required:
        - handler
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1
