site_name: KubeStellar
repo_url: https://github.com/kubestellar/kubestellar
site_url: https://docs.kubestellar.io/

repo_short_name: kubestellar/kubestellar
repo_default_file_path: kubestellar
helm_repo_short_name: kubestellar/helm
helm_repo_default_file_path: helm
brew_repo_short_name: kubestellar/homebrew-kubestellar
brew_repo_default_file_path: homebrew-kubestellar
docs_url: https://docs.kubestellar.io
repo_raw_url: https://raw.githubusercontent.com/kubestellar/kubestellar
edit_uri: edit/main/docs/content
ks_branch: 'main'
ks_tag: 'latest'
ks_latest_regular_release: '0.28.0'
ks_latest_release: '0.28.0'

ks_kind_port_num: '1119'

# Site content
docs_dir: 'content'
# Where to generate
site_dir: 'generated'

nav:
  - Welcome:
      - Landing: index.md
  - What is KubeStellar?:
      - Overview: readme.md
      - Architecture: direct/architecture.md
      - Related:
        - KubeStellar UI: direct/ui-intro.md
        - KubeFlex: direct/kubeflex-intro.md
        - KubeStellar Galaxy: direct/galaxy-intro.md
      - Release-notes: direct/release-notes.md
      - Roadmap: direct/roadmap.md
  - Getting Started: direct/get-started.md
  - User Guide:
      - Guide Overview: direct/user-guide-intro.md
      - Observability: direct/observability.md
      - Getting Started: direct/get-started.md
      - Getting Started from OCM: direct/start-from-ocm.md
      - General Setup:
          - Overview: direct/setup-overview.md
          - Setup limitations: direct/setup-limitations.md
          - Prerequisites: direct/pre-reqs.md
          - KubeFlex Hosting cluster:
            - Acquire cluster for KubeFlex Hosting: direct/acquire-hosting-cluster.md
            - Initialize KubeFlex Hosting cluster: direct/init-hosting-cluster.md
          - Core Spaces:
            - Inventory and Transport Spaces: direct/its.md
            - Workload Description Spaces: direct/wds.md
          - Core Helm chart: direct/core-chart.md
          - Argo CD integration with Core Helm chart: direct/core-chart-argocd.md
          - Workload Execution Clusters:
            - About Workload Execution Clusters: direct/wec.md
            - Register a Workload Execution Cluster: direct/wec-registration.md
      - Usage:
          - Usage limitations: direct/usage-limitations.md
          - KubeStellar API:
              - Overview: direct/control.md
              - API reference (new tab): https://pkg.go.dev/github.com/kubestellar/kubestellar/api/control/v1alpha1
              - Binding: direct/binding.md
              - Transforming desired state: direct/transforming.md
              - Combining reported state: direct/combined-status.md
          - Example Scenarios: direct/example-scenarios.md
          - Third-party integrations:
              - ArgoCD to WDS: direct/argo-to-wds1.md
          - Troubleshooting: direct/troubleshooting.md
          - Known Issues:
              - Overview: direct/known-issues.md
              - Hidden state in kubeconfig: direct/knownissue-kflex-extension.md
              - Kind needs OS reconfig: direct/knownissue-kind-config.md
              - Authorization failure while fetching Helm chart from ghcr.io: direct/knownissue-helm-ghcr.md
              - Missing results in a CombinedStatus object: direct/knownissue-collector-miss.md
              - Kind host not configured for more than two clusters: direct/installation-errors.md
              - Insufficient CPU for your clusters: direct/knownissue-cpu-insufficient-for-its1.md
      - UI (User Interface): ui-docs/ui-overview.md
      - Teardown: direct/teardown.md
  - Contributing:
      - Overview (How to join in): direct/contribute.md
      - Code of Conduct: contribution-guidelines/coc-inc.md
      - Guidelines: contribution-guidelines/contributing-inc.md
      - License: contribution-guidelines/license-inc.md
      - Governance: contribution-guidelines/governance-inc.md
      - Onboarding: contribution-guidelines/onboarding-inc.md
      - Website:
          - Docs Management Overview: contribution-guidelines/operations/document-management.md
      - Security:
          - Policy: contribution-guidelines/security/security-inc.md
          - Contacts: contribution-guidelines/security/security_contacts-inc.md
      - Testing: direct/testing.md
      - Packaging: direct/packaging.md
      - Release Process: direct/release.md
      - Release Testing: direct/release-testing.md
      - Sign-off and Signing Contributions: direct/pr-signoff.md
  - Community:
    - Get Involved: Community/_index.md
    - Contact Us:
        - Mailing List: https://kubestellar.io/join_us
        - Community Meeting Agenda (join mailing list first): https://kubestellar.io/agenda
        - Slack: https://kubestellar.io/slack
        - Medium Blog: https://kubestellar.io/blog
        - YouTube Channel: https://kubestellar.io/tv
        - LinkedIn: https://kubestellar.io/linkedin
        - Reddit: https://www.reddit.com/r/kubestellar/
        - Google Drive: https://drive.google.com/drive/u/1/folders/1p68MwkX0sYdTvtup0DcnAEsnXElobFLS
    - Partners:
        - ArgoCD: Community/partners/argocd.md
        - Turbonomic: Community/partners/turbonomic.md
        - MVI: Community/partners/mvi.md
        - FluxCD: Community/partners/fluxcd.md
        - OpenZiti: Community/partners/openziti.md
        - Kyverno: Community/partners/kyverno.md
  - 'Blog': https://medium.com/@kubestellar/list/predefined:e785a0675051:READING_LIST" target="_blank
  # # - Auto generated:
  #   - ... | auto-generated/*/*.md

theme:
  font:
    text: 'SapceMono'
    code: 'Roboto Mono'
  name: material

  language: en
  # Common files such as images, stylesheets, theme overrides
  custom_dir: 'overrides'
  features:
    # enable the ability to dismiss the announcement bar
    - announce.dismiss
    - content.action.edit
    - content.action.view
    # Enable navigation section index pages, so we don't see Concepts > Concepts
    - navigation.indexes
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.expand
    - navigation.path
    - navigation.footer
    # - navigation.tracking
    # Enable a copy button in code blocks
    - content.code.copy
    # Enable annotations on specific lines in code blocks
    - content.code.annotate
  logo: logo.png
  favicon: favicons/favicon.ico

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: light blue
      accent: cyan
extra:
  # social:
  #   - icon: fontawesome/brands/github
  #     link: 'https://github.com/kubestellar/kubestellar'
  #     name: KubeStellar on GitHub
  #   - icon: fontawesome/brands/linkedin
  #     link: 'https://www.linkedin.com/feed/hashtag/?keywords=kubestellar'
  #     name: KubeStellar on LinkedIn
  #   - icon: fontawesome/brands/medium
  #     link: 'https://medium.com/@kubestellar/list/predefined:e785a0675051:READING_LIST'
  #   - icon: fontawesome/brands/YouTube
  #     link: 'https://www.youtube.com/@kubestellar'
  #     name: KubeStellar on YouTube
  #   - icon: fontawesome/brands/slack
  #     link: 'https://kubernetes.slack.com/archives/C058SUSL5AA'
  #     name: KubeStellar on Slack
  #   - icon: fontawesome/solid/paper-plane
  #     link: mailto:kubestellar-dev@google.groups.com
  #     name: Email us
  version:
    default: latest
    # Enable mike for multi-version selection
    provider: mike
  analytics:
    provider: google
    property: G-SR5TD1CXY7
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/kubestellar/kubestellar/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yaml&title=bug%3A+" target="_blank" rel="noopener">feedback form</a>.

plugins:
  - i18n:
      default_language: en
      languages:
        en: "English"
        fr: "Fran√ßais"



  # apidocs
  # - mkdocs-apidoc
  # Docs site search
  - search
  - mermaid2:
      version: 10.0.2
  # Use Jinja macros in .md files
  - open-in-new-tab
  - include-markdown
  - macros:
      include_dir: 'overrides'
      module_name: 'main'
  # Configure multiple language support

  # - redirects:
  #       redirect_maps:
  #           'docs': 'docs/Coding%20Milestones/PoC2023q1/outline/'
  #           'old/file.md': 'new/file.md'
  #           'some_file.md': 'http://external.url.com/foobar'

markdown_extensions:
  - markdown_captions
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - toc:               # Builds a table of contents
      permalink: "#"
  # Code block highlighting
  - pymdownx.highlight:
      # Allows linking directly to specific lines in code blocks
      anchor_linenums: true
      pygments_lang_class: true
  # Inline code block highlighting
  - pymdownx.inlinehilite
  # Lets you embed content from another file
  - pymdownx.snippets
  # Arbitrary nesting of code/content blocks inside each other
  - pymdownx.tabbed:
      alternate_style: true
  # Enable note/warning/etc. callouts
  - admonition

# Our CSS
extra_css:
  - stylesheets/kubestellar.css

# Live reload if any of these change when running 'mkdocs serve'
watch:
  - mkdocs.yml
  - content
  - overrides
