name: Add Help Wanted, Good First Issue, or Hacktober Fest Labels

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  label-on-comment:
    if: |
     github.event.comment.body == '/help-wanted' ||
     github.event.comment.body == '/good-first-issue' ||
     github.event.comment.body == '/hacktober-fest' ||
     github.event.comment.body == '/triage-accepted'

    runs-on: ubuntu-latest
    steps:
      - name: Add label based on comment
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        with:
          script: |
            const comment = context.payload.comment.body.trim().toLowerCase();
            const issue_number = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            // Handle triage acceptance
            if (comment === '/triage-accepted') {
             // Remove need-triage if it exists
             try {
              await github.rest.issues.removeLabel({
                owner,
                repo,
                issue_number,
                name: 'need-triage',
              });
             } catch (_) {
             // ignore if label does not exist
            }
             // Add triage-accepted
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels: ['triage-accepted'],
              });
             return;
            }
            let label = null;
            if (comment === '/help-wanted') {
              label = 'help wanted';
            } else if (comment === '/good-first-issue') {
              label = 'good first issue';
            } else if (comment === '/hacktober-fest') {
              label = 'hacktober-fest';
            }

            if (label) {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels: [label],
              });
              console.log(`Added label: ${label}`);
            } else {
              console.log('No matching label to apply.');
            }
