name: Create KubeStellar bi-Weekly Meeting issue
run-name: Create KubeStellar bi-Weekly Meeting issue - ${{ github.ref_name }}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 4"
    
jobs:
  issue:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'kubestellar'
    steps:
      - name: Check Bi-Weekly Condition
        id: check_condition
        run: |
          # Calculate the week number
          week_number=$(($(date +\%U) % 2))

          # Set the output variable based on the week number
          if [[ $week_number -eq 0 ]]; then
            echo "run_workflow=true" >> $GITHUB_OUTPUT
          else
            echo "run_workflow=false" >> $GITHUB_OUTPUT
          fi
          
      - uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.GH_ALL_PROJECT_TOKEN }}
          persist-credentials: 'false'
          
      - uses: JasonEtco/create-an-issue@v2
        if: steps.check_condition.outputs.run_workflow == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ALL_PROJECT_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/community_meeting.md
