name: docs-ecutable - example1
run-name: docs-ecutable - example1 - ${{ github.ref_name }}

on:
  workflow_call:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request:
    branches:
      - main
      - "release-*"
      - space-mgt
  push:
    branches:
      - main
      - "release-*"
      - space-mgt
    tags:
      - 'v*'

env:
  docs-ecutable-filename: example1
  docs-ecutable-dirname: "Coding Milestones/PoC2023q1/example1"

jobs:
  docs-ecutable:
    #if: github.repository_owner == 'kubestellar'
    name: docs-ecutable - for example1 e2e
    runs-on: ubuntu-latest
    outputs:
      docs-ecutable-dirname: ${{ steps.step1.outputs.docs-ecutable-dirname }}
    steps:
      - id: step1
        run: echo "docs-ecutable-dirname=${{ env.docs-ecutable-dirname }}" >> "$GITHUB_OUTPUT"

      - run: echo ${{ steps.step1.outputs.docs-ecutable-dirname }}

      - uses: actions/checkout@v4.1.1
      
      - uses: actions/setup-go@v5
        with:
          go-version: v1.19
          cache: true

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install PyPy
        uses: actions/setup-python@v5 
        with:
          python-version: 'pypy3.9' 

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        # with:
        #  version: 'v1.28.3'
        id: install

      - run: |
          make MANIFEST="${{ env.docs-ecutable-dirname }}" \
          execute-html

      - name: Dump mailbox-controller log
        if: always()
        run: cat /tmp/mailbox-controller.log

      - name: Dump where-resolver log
        if: always()
        run: cat /tmp/where-resolver.log

      - name: Tail placement-translator log
        if: always()
        run: |
          wc /tmp/placement-translator.log
          tail /tmp/placement-translator.log

      - name: Dump placement-translator log
        if: always()
        run: cat /tmp/placement-translator.log
