name: Generate and push docs
run-name: Generate and push docs - ${{ github.ref_name }}

on:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  push:
    branches:
      - "release-*"
      - "doc-*"
      - main
    paths:
      - "docs/**"
      - "*.md"
      - ".github/workflows/docs-gen-and-push.yaml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}

jobs:
  debug:
    name: print relevant info
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          echo "github.actor=${{ github.actor }}"
          echo "github.action_ref=${{ github.action_ref }}"
          echo "github.event_name=${{ github.event_name }}"
          echo "github.head_ref=$GITHUB_HEAD_REF"
          echo "github.ref=${{ github.ref }}"
          echo "github.ref_name=${{ github.ref_name }}"
          echo "github.repository_owner=${{ github.repository_owner }}"
          echo "github.triggering_actor=${{ github.triggering_actor }}"
          echo "GITHUB_ACTION_REF=$GITHUB_ACTION_REF"

  generate-and-push:
    if: github.repository_owner == 'kubestellar' || github.repository_owner == github.actor
    name: Generate and push docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          token: ${{ github.repository_owner == 'kubestellar' && secrets.GH_ALL_PROJECT_TOKEN || github.token }}
          persist-credentials: "true"

      - run: git fetch origin gh-pages

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.10"
          cache: "pip"

      - run: make deploy-docs

  call-crawl:
    needs: generate-and-push
    uses: ./.github/workflows/broken-links-crawler.yml
