name: docs-ecutable - example1

on:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request:
    branches:
      - main
      - "release-*"
    paths:
      - "docs/content/Coding Milestones/PoC2023q1/example1.md"
      - "docs/content/Coding Milestones/PoC2023q1/example1-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/common-subs/**"
      - ".github/workflows/docs-ecutable-example1.yml"
      - "docs/scripts/docs-ecutable.sh"
  push:
    branches:
      - main
      - "release-*"
    paths:
      - "docs/content/Coding Milestones/PoC2023q1/example1.md"
      - "docs/content/Coding Milestones/PoC2023q1/example1-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/common-subs/**"
      - ".github/workflows/docs-ecutable-example1.yml"
      - "docs/scripts/docs-ecutable.sh"

env:
  docs-ecutable-filename: example1
  docs-ecutable-md-filename: "'docs/content/Coding Milestones/PoC2023q1/example1.md'"

permissions:
  contents: write

jobs:
  docs-ecutable:
    name: docs-ecutable - for example1 e2e
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe-to-test') || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    outputs:
      docs-ecutable-filename: ${{ steps.step1.outputs.docs-ecutable-filename }}
    steps:
      - id: step1
        run: echo "docs-ecutable-filename=${{ env.docs-ecutable-filename }}" >> "$GITHUB_OUTPUT"

      - run: echo ${{ steps.step1.outputs.docs-ecutable-filename }}

      - uses: actions/checkout@v3.5.3
        with:
          token: ${{ secrets.GH_ALL_PROJECT_TOKEN }}
          persist-credentials: 'false'

      - name: echo fetching workflow_dispatch branch
        run: git fetch origin ${GITHUB_REF##*/}
        # run: echo running on branch ${GITHUB_REF##*/}
        if: github.event_name == 'workflow_dispatch'

      - name: echo fetching push or pull_request branch
        run: git fetch origin ${{ github.ref_name }}
        # run: echo running on branch ${{ github.ref_name }}
        if: github.event_name == 'push' || github.event_name == 'pull_request'

      - uses: actions/setup-go@v4
        with:
          go-version: v1.19
          cache: true

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install
  
      - run: |
          make MANIFEST="${{ env.docs-ecutable-md-filename }}" \
          docs-ecutable