name: docs-ecutable - QS
run-name: docs-ecutable - QS - ${{ github.ref_name }}

on:
  workflow_call:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request:
    branches:
      - main
      - "release-*"
    paths:
      - "docs/content/Getting-Started/quickstart.md"
      - "docs/content/Getting-Started/quickstart-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/common-subs/**"
      - ".github/workflows/docs-ecutable-qs.yml"
      - "docs/scripts/docs-ecutable.sh"
  push:
    branches:
      - main
      - "release-*"
    paths:
      - "docs/content/Getting-Started/quickstart.md"
      - "docs/content/Getting-Started/quickstart-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/common-subs/**"
      - ".github/workflows/docs-ecutable-qs.yml"
      - "docs/scripts/docs-ecutable.sh"
    tags:
      - 'v*'
      
env:
  docs-ecutable-filename: qs
  docs-ecutable-md-filename: "'docs/content/Getting-Started/quickstart.md'"

jobs:
  docs-ecutable:
    #if: github.repository_owner == 'kubestellar'
    name: docs-ecutable - for quickstart e2e
    runs-on: ubuntu-latest
    outputs:
      docs-ecutable-filename: ${{ steps.step1.outputs.docs-ecutable-filename }}
    steps:
      - id: step1
        run: echo "docs-ecutable-filename=${{ env.docs-ecutable-filename }}" >> "$GITHUB_OUTPUT"

      - run: echo ${{ steps.step1.outputs.docs-ecutable-filename }}

      - uses: actions/checkout@v3.5.3
      
      - uses: actions/setup-go@v4
        with:
          go-version: v1.19
          cache: true

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.4'
        id: install

      - run: kubectl version
      
      - run: |
          make MANIFEST="${{ env.docs-ecutable-md-filename }}" \
          docs-ecutable
