name: Greetings

on:
  pull_request_target:
    # No need on most types
    types: [opened, reopened]
  issues:
    # No need on most types
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@3c71ce730280171fd1cfb57c00c774f8998586f7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for contributing your first Issue to KubeStellar. We are delighted to have you in our Universe!"
          pr-message: "Thank you for submitting your first Pull Request to KubeStellar. We are delighted to have you in our Universe!"