name: Add Issues to Project

on:
  issues:
    types: [opened]
env:
  GITHUB_API_TOKEN: ${{ secrets.NEW_ISSUE_ACTION_PAT }}

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
    - name: Assign new issues to the project
      uses: tcassou/project-bot@2.0.0
      with:
        project_url: 'https://github.com/orgs/kcp-dev/projects/12'
