name: Run Doc Shells - Placement

on:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request:
    branches:
      - main
      - "release-*"
    paths:
      - "docs/content/Coding Milestones/PoC2023q1/placement-translator.md"
      - "docs/content/Coding Milestones/PoC2023q1/mailbox-controller-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/kubestellar-scheduler-subs/**"
      - ".github/workflows/run-doc-shells-placement.yml"
  push:
    branches:
      - main
      - "release-*"
    paths:
      - "docs/content/Coding Milestones/PoC2023q1/placement-translator.md"
      - "docs/content/Coding Milestones/PoC2023q1/mailbox-controller-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/kubestellar-scheduler-subs/**"
      - ".github/workflows/run-doc-shells-placement.yml"

permissions:
  contents: write

# concurrency:
#   group: ${{ github.workflow }}

jobs:
  run-doc-shells:
    name: Run doc shells - for placement e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: git fetch origin release-0.2

      - uses: actions/setup-go@v4
        with:
          go-version: v1.19
          cache: true

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install
  
      - run: |
          make MANIFEST="'content/Coding Milestones/PoC2023q1/placement-translator.md'" \
          run-doc-shells
